### ISSUE TITLE
Compilation error: ‘ZMQ_STREAM_NOTIFY’ was not declared in this scope

### ISSUE THREAD

**Issue by sneetsher** [kevinkreiser/prime_server#37]
I am trying to build it on Ubuntu 16.04 Beta. (to answer your Q in AU). I followed the steps from read-me file.

`make test` raise the following error:
```
$ make test
  CXX      src/libprime_server_la-prime_server.lo
src/prime_server.cpp: In constructor ‘prime_server::client_t::client_t(zmq::context_t&, const string&, const request_function_t&, const collect_function_t&, size_t)’:
src/prime_server.cpp:23:23: error: ‘ZMQ_STREAM_NOTIFY’ was not declared in this scope
     server.setsockopt(ZMQ_STREAM_NOTIFY, &enabled, sizeof(enabled));
                       ^
src/prime_server.cpp: In constructor ‘prime_server::server_t<request_container_t, request_info_t>::server_t(zmq::context_t&, const string&, const string&, const string&, bool, size_t)’:
src/prime_server.cpp:91:23: error: ‘ZMQ_STREAM_NOTIFY’ was not declared in this scope
     client.setsockopt(ZMQ_STREAM_NOTIFY, &enabled, sizeof(enabled));
                       ^
Makefile:916: recipe for target 'src/libprime_server_la-prime_server.lo' failed
make: *** [src/libprime_server_la-prime_server.lo] Error 1
```

Current dependencies installed:
```
$ apt-cache policy  libcurl4-openssl-dev libzmq3-dev
libcurl4-openssl-dev:
  Installed: 7.47.0-1ubuntu2
  Candidate: 7.47.0-1ubuntu2
  Version table:
 *** 7.47.0-1ubuntu2 500
        500 http://dz.archive.ubuntu.com/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
libzmq3-dev:
  Installed: 4.1.4-7
  Candidate: 4.1.4-7
  Version table:
 *** 4.1.4-7 500
        500 http://dz.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by kevinkreiser** [comment]
interesting, there must be some differences between the libzmq3 package in previous versions of ubuntu (i know they were messing with that part of the library so its not surprising). I'll see if i can push up a fix to this to get it working with the latest package. thanks so much for your help!

**Comment by kevinkreiser** [comment]
i have it working on ubuntu 16.04 beta now. ill test it out on older versions of the package, get a pr in, and merge this so you can give it another try! thanks again so much!
